In [67]:
import pandas as pd
df = pd.read_csv("/Volumes/mac1/data/limb/best_hpo_terms_with_parents.csv")
#df.head()

In [68]:
import ast

df["Parents_list"] = df["Parents"].apply(ast.literal_eval)

def extract_cluster(parents):
    parents = [p.lower() for p in parents]
    if any(x in p for p in parents for x in [
            "glucose", "insulin", "hyperglycemia", "diabetes", "metabolism/homeostasis"
        ]):
            return "Glucose/Insulin"
    
    if any(x in p for p in parents for x in [
        "neoplasm", "tumor", "cancer", "malignancy", "carcinoma", "sarcoma", "adenoma", "lymphoma", "melanoma"
    ]):
        return "Neoplasm"

    if any(x in p for p in parents for x in ["renal", "urinary", "kidney", "ureter"]):
        return "Renal"

    if any(x in p for p in parents for x in ["cardiac", "heart", "aorta", "ventricle", "septum", "artery", "vascular"]):
        return "Cardiac"

    if any(x in p for p in parents for x in ["skeletal", "bone", "vertebra", "sternum", "clavicle", 'growth', 'joint',"springel","pes","tarsa","carpa"
                                            "limb", "digit", "phalange", "metacarpal", "metatarsal", "toe", "finger","joint","sacro","valgus","varus"]):
        return "Skeletal"

    if any(x in p for p in parents for x in ["ear", "cochlea", "auditory"]):
        return "Auditory"

    if any(x in p for p in parents for x in ["eye", "iris", "optic", "lens"]):
        return "Ocular"

    if any(x in p for p in parents for x in ["genitalia", "uterus", "vagina", "scrotum", "reproductive"]):
        return "Genital"

    if any(x in p for p in parents for x in ["pancreas", "intestine", "colon", "abdominal", "digestive"]):
        return "GI"

    # Blood-related
    if any(x in p for p in parents for x in [
        "hemato", 'anemia', 'leukemia', 'lymphoma', 'thrombocytopenia', 'coagulation'
    ]):
        return "Blood"

    # Endocrine
    if any(x in p for p in parents for x in [
        "endocrine", "pituitary", "thyroid", "parathyroid", "gland",'puberty', 'hormone', 'adrenal', 'cortisol', 'aldosterone', 'androgen', 'estrogen', 'testosterone'
    ]):
        return "Endocrine"

    # Skin / dermatologic
    if any(x in p for p in parents for x in [
        "skin", "derm", "integument", "nail", "adnexa", 'hair'
    ]):
        return "Skin"

    # Placenta / umbilical cord / pregnancy
    if any(x in p for p in parents for x in [
        "placenta", "umbilical", "prenatal", "fetal", "pregnancy", "gestation"
    ]):
        return "Placenta/Prenatal"

    if any(x in p for p in parents for x in [
            "palate", "pharynx", "larynx", "esophagus", "throat", 'pulmon', 'sinus', 'trachea', 'broncho', 'alveol', 'lung', 'respiratory', 'nasal' 
        ]):
            return "Oral/Respiratory"
    if any(x in p for p in parents for x in [
            "face", "nose", "mouth", "langue", 'toungue', 'cheek', 'jaw', 'mandible', 'maxilla', 'lip', 'palate', 'philturm', 'pit', 'auricular'
        ]):
            return "Face"
    if any(x in p for p in parents for x in [
                "brain", "cerebrum", "cerebellum", "spinal cord", "nervous system", "myelo", "neuron", "nerve","autism"
            ]):
                return "Nervous System"
    return "Other"



df["Cluster"] = df["Parents_list"].apply(extract_cluster)

In [69]:
df.to_csv("/Volumes/mac1/data/limb/best_hpo_terms_with_parents_and_organs.csv", index=False)

In [59]:
import plotly.express as px

fig = px.sunburst(
    df,
    path=["Cluster", "Term"],
    values="Combined Score",
    color="Cluster"
)
import plotly.io as pio
pio.renderers.default = "browser"

fig.show()

In [70]:
import re
df["TF_family"] = df["Genes"].apply(lambda x: [re.sub(r"[\d-]+$", "", tf) for tf in x.split(";")])

In [72]:
df.to_csv("/Volumes/mac1/data/limb/best_hpo_terms_with_parents_and_clusters_and_TFfamilies.csv")

In [73]:
df= pd.read_csv("/Volumes/mac1/data/limb/best_hpo_terms_with_parents_and_clusters_and_TFfamilies.csv")
#df.head()

In [62]:
import plotly.express as px

fig = px.sunburst(
    df,
    path=["Cluster", "Term", "TF_family"],
    values="Combined Score",
    color="Cluster"
)

fig.update_layout(
    margin=dict(t=0, l=0, r=0, b=0)
)

fig.show()

In [63]:
df.to_csv("/Volumes/mac1/data/limb/best_hpo_terms_with_parents_and_clusters_and_TFfamilies.csv", index=False)

In [64]:
import pandas as pd
df= pd.read_csv("/Volumes/mac1/data/limb/best_hpo_terms_with_parents_and_clusters_and_TFfamilies.csv")

In [65]:
df.Term[1].split("(")[0].strip()

'Abnormal pancreas size'

In [75]:
from pyvis.network import Network
import networkx as nx
import ast
import numpy as np

# --- Build graph with top 150 HPO ---
df_top = df.nlargest(30, "Combined Score")
df_top = df_top[df_top["Cluster"] != "Other"]
#df_top = df

G = nx.Graph()

# --- Add TF nodes ---
for tf_list in df_top["TF_family"]:
    tf_list = ast.literal_eval(tf_list)
    for tf in tf_list:
        G.add_node(tf, type="TF")

# --- Add Cluster nodes ---
for cl in df_top["Cluster"].unique():
    G.add_node(cl, type="Cluster")

# --- Add HPO nodes ---
for term in df_top["Term"].unique():
    G.add_node(term, type="HPO")

# --- Add weighted edges ---
for _, row in df_top.iterrows():
    tf_list = ast.literal_eval(row["TF_family"])
    for tf in tf_list:
        G.add_edge(tf, row["Cluster"], combined=row["Combined Score"])
    G.add_edge(row["Cluster"], row["Term"], combined=row["Combined Score"])

# --- 2D layout ---
pos2d = nx.kamada_kawai_layout(G)

# --- Add pseudo‑3D depth ---
pos3d = {n: np.append(pos2d[n], np.random.uniform(-1, 1)) for n in G.nodes}

# --- PyVis graph ---
net = Network(
    height="900px",
    width="100%",
    bgcolor="#ffffff",
    font_color="black",
    cdn_resources="in_line"
)

# --- Activate physics (required for movement) ---
net.set_options("""
{
"nodes": {
    "font": {"size": 25}
  },
  "physics": {
    "enabled": true,
    "barnesHut": {
      "gravitationalConstant": -8000,
      "centralGravity": 0.3,
      "springLength": 95,
      "springConstant": 0.04,
      "damping": 0.09
    }
  }
}
""")

# --- Add nodes with pseudo‑3D coordinates ---
for n in G.nodes:
    x, y, z = pos3d[n]
    net.add_node(
        n,
        x=float(x),
        y=float(y),
        z=float(z),
        color=("red" if G.nodes[n]["type"]=="TF"
               else "blue" if G.nodes[n]["type"]=="Cluster"
               else "green"),
        size=(25 if G.nodes[n]["type"]=="TF"
              else 20 if G.nodes[n]["type"]=="Cluster"
              else 10)
    )

# --- Add edges with weights ---
for u, v, data in G.edges(data=True):
    score = data["combined"]
    net.add_edge(
        u, v,
        value=score,
        width=score/20,
        title=f"Combined Score: {score:.2f}",
        color="gray"
    )

net.write_html("/Volumes/mac1/data/limb/network_pseudo3D.html")

In [6]:
rows = [
    {"source": u, "target": v, **attrs}
    for u, v, attrs in G.edges(data=True)
]

df = pd.DataFrame(rows)
df.to_csv("/Volumes/mac1/data/limb/results/edges.csv", index=False)

« Le graphe pondéré TF–Cluster–HPO montre que les relations ne sont pas uniformes :
les arêtes les plus épaisses correspondent aux phénotypes les plus enrichis.
Les TFs TBX, GATA, HOXD et HNF1B apparaissent comme des hubs majeurs,
connectant plusieurs clusters avec des poids élevés.
Cela révèle des modules transcriptionnels cohérents et des axes biologiques partagés. »

In [88]:
df.head()

,Gene_set,Term,Overlap,P-value,Adjusted P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes,Parents,Parents_list,Cluster,TF_family
0,Human_Phenotype_Ontology,Morphological abnormality of the inner ear (HP...,3/11,0.000306,0.034343,0,0,29.608500,239.572313,FOXI1;SOX10;POU3F4,"['Abnormal inner ear morphology', 'Abnormality...","['Abnormal inner ear morphology', 'Abnormality...",Auditory,"['FOXI', 'SOX', 'POU3F']"
1,Human_Phenotype_Ontology,Abnormal pancreas size (HP:0012094),3/11,0.000306,0.034343,0,0,29.608500,239.572313,PDX1;GATA6;HNF1B,"['Abnormal pancreas size', 'Abnormal pancreas ...","['Abnormal pancreas size', 'Abnormal pancreas ...",GI,"['PDX', 'GATA', 'HNF1B']"
2,Human_Phenotype_Ontology,Ureteral stenosis (HP:0000071),3/14,0.000657,0.049109,0,0,21.530182,157.778151,HOXD13;HNF1B;HOXA13,"['Ureteral stenosis', 'Ureteral obstruction', ...","['Ureteral stenosis', 'Ureteral obstruction', ...",Renal,"['HOXD', 'HNF1B', 'HOXA']"
3,Human_Phenotype_Ontology,Bifid scrotum (HP:0000048),4/22,0.000153,0.034343,0,0,17.607318,154.696128,HOXD13;SOX9;HOXA13;MNX1,"['Bifid scrotum', 'Abnormal scrotum morphology...","['Bifid scrotum', 'Abnormal scrotum morphology...",Renal,"['HOXD', 'SOX', 'HOXA', 'MNX']"
4,Human_Phenotype_Ontology,Concave nail (HP:0001598),2/8,0.004244,0.119014,0,0,26.216467,143.199698,LMX1B;HOXC13,"['Concave nail', 'Nail dysplasia', 'Abnormal n...","['Concave nail', 'Nail dysplasia', 'Abnormal n...",Skin,"['LMX1B', 'HOXC']"

In [94]:
import ast

def tf_union_from_terms_and_clusters(df, term_keywords, clusters):
    tf_set = set()

    # 1) Terms contenant les mots-clés (vertebr, trache, esoph, anal)
    mask_terms = df["Term"].str.contains("|".join(term_keywords), case=False, na=False)
    print(f"Nombre de termes correspondant aux mots-clés {term_keywords}: {df[mask_terms]}")
    sub_terms = df[mask_terms]

    for tf_str in sub_terms["TF_family"]:
        for tf in ast.literal_eval(tf_str):
            if tf != "Other":
                tf_set.add(tf)

    # 2) Clusters Cardiac + Skeletal
    mask_clusters = df["Cluster"].isin(clusters)
    sub_clusters = df[mask_clusters]

    for tf_str in sub_clusters["TF_family"]:
        for tf in ast.literal_eval(tf_str):
            if tf != "Other":
                tf_set.add(tf)

    return tf_set


# --- VACTERL definition précise ---
vacterl_term_keywords = ["vertebr", "trache", "esoph", "anal"]
vacterl_clusters = ["Cardiac", "Skeletal"]

tf_vacterl = tf_union_from_terms_and_clusters(
    df,
    term_keywords=vacterl_term_keywords,
    clusters=vacterl_clusters
)

print("TFs actifs dans VACTERL (définition précise) :")
print(sorted(tf_vacterl))

Nombre de termes correspondant aux mots-clés ['vertebr', 'trache', 'esoph', 'anal']:                      Gene_set  \
27   Human_Phenotype_Ontology
49   Human_Phenotype_Ontology
54   Human_Phenotype_Ontology
57   Human_Phenotype_Ontology
122  Human_Phenotype_Ontology
148  Human_Phenotype_Ontology
174  Human_Phenotype_Ontology
234  Human_Phenotype_Ontology
235  Human_Phenotype_Ontology
272  Human_Phenotype_Ontology
286  Human_Phenotype_Ontology
295  Human_Phenotype_Ontology
310  Human_Phenotype_Ontology
350  Human_Phenotype_Ontology
437  Human_Phenotype_Ontology

                                                  Term Overlap   P-value  \
27                      Tracheal stenosis (HP:0002777)    3/23  0.002938
49        Abnormal vertebral ossification (HP:0100569)    2/17  0.019128
54   Abnormality of the intervertebral disk (HP:000...    2/19  0.023656
57   Aplasia/Hypoplasia involving the vertebral col...    3/36  0.010499
122                Vertebral arch anomaly (HP:0008438)    1/10  0.119562
148                      Vertebral fusion (HP:0002948)    2/29  0.051738
174                    Esophageal atresia (HP:0002032)    1/11  0.130705
234   Aplasia/Hypoplasia of the vertebrae (HP:0008515)    1/13  0.152571
235                  Vertebral hypoplasia (HP:0008417)    1/13  0.152571
272                          Anal atresia (HP:0002023)    2/39  0.087059
286                         Anal stenosis (HP:0002025)    1/15  0.173890
295                      Choanal stenosis (HP:0000452)    1/15  0.173890
310                        Tracheomalacia (HP:0002779)    1/16  0.184348
350                      Esophageal varix (HP:0002040)    1/18  0.204870
437                         Hemivertebrae (HP:0002937)    1/24  0.263402

     Adjusted P-value  Old P-value  Old Adjusted P-value  Odds Ratio  \
27           0.089870            0                     0   11.836200
49           0.178795            0                     0   10.481806
54           0.196553            0                     0    9.247715
57           0.141338            0                     0    7.168727
122          0.328429            0                     0    8.702822
148          0.270577            0                     0    5.819684
174          0.330693            0                     0    7.832143
234          0.340002            0                     0    6.526124
235          0.340002            0                     0    6.526124
272          0.316208            0                     0    4.244643
286          0.350383            0                     0    5.593254
295          0.350383            0                     0    5.593254
310          0.356512            0                     0    5.220106
350          0.360936            0                     0    4.605509
437          0.386208            0                     0    3.403037

     Combined Score               Genes  \
27        69.006153  SMAD4;FOXI1;HOXD13
49        41.472231         SOX9;NKX3-2
54        34.624540         HES7;HOXD13
57        32.663856      NFIX;SOX9;MNX1
122       18.484125               SMAD4
148       17.235412          HES7;SMAD4
174       15.936956              HOXD13
234       12.269919                SOX9
235       12.269919                SOX9
272       10.361891         HOXD13;MNX1
286        9.784464                MNX1
295        9.784464                NFIX
310        8.826833                SOX9
350        7.301474               SMAD4
437        4.539903                HES7

                                               Parents  \
27   ['Tracheal stenosis', 'Abnormal tracheal morph...
49   ['Abnormally ossified vertebrae', 'Abnormal en...
54   ['Abnormal intervertebral disk morphology', 'A...
57   ['Aplasia/Hypoplasia involving the vertebral c...
122  ['Vertebral arch anomaly', 'Abnormal vertebral...
148  ['Vertebral fusion', 'Vertebral segmentation d...
174  ['Esophageal atresia', 'Abnormal esophagus mor...
234  ['Aplasia/Hypoplasia of the vertebrae', 'Abnor...
235  ['Vertebral hypoplasia', 'Aplasia/Hypoplasia o...
272  ['Anal atresia', 'Abnormal anus morphology', '...
286  ['Anal stenosis', 'Abnormal anus morphology', ...
295  ['Choanal stenosis', 'Abnormal choanae morphol...
310  ['Tracheomalacia', 'Abnormal tracheal morpholo...
350  ['Esophageal varix', 'Abnormal esophagus morph...
437  ['Hemivertebrae', 'Abnormal vertebral body mor...

                                          Parents_list           Cluster  \
27   ['Tracheal stenosis', 'Abnormal tracheal morph...  Oral/Respiratory
49   ['Abnormally ossified vertebrae', 'Abnormal en...          Skeletal
54   ['Abnormal intervertebral disk morphology', 'A...          Skeletal
57   ['Aplasia/Hypoplasia involving the vertebral c...          Skeletal
122  ['Vertebral arch anomaly', 'Abnormal vertebral...          Skeletal
148  ['Vertebral fusion', 'Vertebral segmentation d...          Skeletal
174  ['Esophageal atresia', 'Abnormal esophagus mor...                GI
234  ['Aplasia/Hypoplasia of the vertebrae', 'Abnor...          Skeletal
235  ['Vertebral hypoplasia', 'Aplasia/Hypoplasia o...          Skeletal
272  ['Anal atresia', 'Abnormal anus morphology', '...                GI
286  ['Anal stenosis', 'Abnormal anus morphology', ...                GI
295  ['Choanal stenosis', 'Abnormal choanae morphol...  Oral/Respiratory
310  ['Tracheomalacia', 'Abnormal tracheal morpholo...  Oral/Respiratory
350  ['Esophageal varix', 'Abnormal esophagus morph...                GI
437  ['Hemivertebrae', 'Abnormal vertebral body mor...          Skeletal

                    TF_family
27   ['SMAD', 'FOXI', 'HOXD']
49             ['SOX', 'NKX']
54            ['HES', 'HOXD']
57     ['NFIX', 'SOX', 'MNX']
122                  ['SMAD']
148           ['HES', 'SMAD']
174                  ['HOXD']
234                   ['SOX']
235                   ['SOX']
272           ['HOXD', 'MNX']
286                   ['MNX']
295                  ['NFIX']
310                   ['SOX']
350                  ['SMAD']
437                   ['HES']
TFs actifs dans VACTERL (définition précise) :
['FOXC', 'FOXG', 'FOXI', 'GATA', 'HES', 'HMGA', 'HNF1B', 'HOXA', 'HOXD', 'IRF', 'IRX', 'LMX1B', 'MEIS', 'MNX', 'MSX', 'NFIX', 'NKX', 'PAX', 'PDX', 'POU1F', 'PPARG', 'SMAD', 'SOX', 'TBX', 'THRB']

In [116]:
fanconi_term_keywords = [
     "radial", "radius",
    "anemia", "erythro", "hemato", "blood",
    "tumor", "neoplasm", "malign"
]



tf_fanconi = tf_union_from_terms_and_clusters(
    df,
    term_keywords=fanconi_term_keywords,
    clusters=[]
)

print("TFs actifs dans Fanconi :", sorted(tf_fanconi))

Nombre de termes correspondant aux mots-clés ['radial', 'radius', 'anemia', 'erythro', 'hemato', 'blood', 'tumor', 'neoplasm', 'malign']:                      Gene_set  \
14   Human_Phenotype_Ontology
84   Human_Phenotype_Ontology
101  Human_Phenotype_Ontology
179  Human_Phenotype_Ontology
213  Human_Phenotype_Ontology
257  Human_Phenotype_Ontology
270  Human_Phenotype_Ontology
312  Human_Phenotype_Ontology
340  Human_Phenotype_Ontology
382  Human_Phenotype_Ontology
383  Human_Phenotype_Ontology
386  Human_Phenotype_Ontology
396  Human_Phenotype_Ontology
418  Human_Phenotype_Ontology
423  Human_Phenotype_Ontology
425  Human_Phenotype_Ontology

                                                  Term Overlap   P-value  \
14   Abnormal umbilical cord blood vessels (HP:0011...    2/10  0.006708
84                           Hematochezia (HP:0002573)     1/8  0.096847
101                     Microcytic anemia (HP:0001935)    2/25  0.039502
179                    Embryonal neoplasm (HP:0002898)    2/31  0.058297
213            Radial deviation of finger (HP:0009466)   8/229  0.008920
257           Neoplasm of the oral cavity (HP:0100649)    1/14  0.163298
270                 Neoplasm of the liver (HP:0002896)    2/39  0.087059
312                    Hypochromic anemia (HP:0001931)    1/16  0.184348
340           Neoplasm of striated muscle (HP:0009728)    1/18  0.204870
382        Abnormality of the radial head (HP:0003995)    1/21  0.234693
383       Neoplasm of the small intestine (HP:0100833)    1/21  0.234693
386                         Absent radius (HP:0003974)    1/21  0.234693
396                 Spontaneous hematomas (HP:0007420)    1/22  0.244385
418                   Neuroblastic tumors (HP:0004376)    1/23  0.253954
423       Primitive neuroectodermal tumor (HP:0030065)    1/23  0.253954
425  Peripheral primitive neuroectodermal neoplasm ...    1/23  0.253954

     Adjusted P-value  Old P-value  Old Adjusted P-value  Odds Ratio  \
14           0.132781            0                     0   19.660359
84           0.316208            0                     0   11.190476
101          0.237368            0                     0    6.833189
179          0.270577            0                     0    5.417777
213          0.141338            0                     0    2.884994
257          0.346687            0                     0    6.023810
270          0.316208            0                     0    4.244643
312          0.356512            0                     0    5.220106
340          0.360936            0                     0    4.605509
382          0.382351            0                     0    3.914087
383          0.382351            0                     0    3.914087
386          0.382351            0                     0    3.914087
396          0.382351            0                     0    3.727513
418          0.382351            0                     0    3.557900
423          0.382351            0                     0    3.557900
425          0.382351            0                     0    3.557900

     Combined Score                                            Genes  \
14        98.389031                                     GATA6;HOXD13
84        26.125559                                            SMAD4
101       22.080713                                       SMAD4;IRX5
179       15.398454                                        NFIX;MNX1
213       13.615637  TBX1;SMAD4;GATA6;HMGA2;HOXD13;LMX1B;HOXA13;TBX2
257       10.916211                                            SOX10
270       10.361891                                     POU6F2;HNF1A
312        8.826833                                             IRX5
340        7.301474                                             PAX7
382        5.673375                                            LMX1B
383        5.673375                                            SMAD4
386        5.673375                                           HOXD13
396        5.252112                                            SMAD4
418        4.876471                                           PHOX2B
423        4.876471                                           PHOX2B
425        4.876471                                           PHOX2B

                                               Parents  \
14   ['Abnormal umbilical cord blood vessel morphol...
84   ['Hematochezia', 'Gastrointestinal hemorrhage'...
101  ['Microcytic anemia', 'Anemia of inadequate pr...
179  ['Embryonal neoplasm', 'Neoplasm by histology'...
213  ['Radial deviation of finger', 'Deviation of f...
257  ['Neoplasm of the oral cavity', 'Abnormal oral...
270  ['Neoplasm of the liver', 'Abnormality of the ...
312  ['Hypochromic anemia', 'Anemia of inadequate p...
340  ['Neoplasm of striated muscle', 'Abnormality o...
382  ['Abnormality of the radial head', 'Abnormal m...
383  ['Neoplasm of the small intestine', 'Neoplasm ...
386  ['Absent radius', 'Absent forearm bone', 'Apla...
396  ['Spontaneous hematomas', 'Subcutaneous hemorr...
418  ['Neuroblastic tumor', 'Malignant neoplasm of ...
423  ['Primitive neuroectodermal tumor', 'Neuroepit...
425  ['Peripheral primitive neuroectodermal neoplas...

                                          Parents_list   Cluster  \
14   ['Abnormal umbilical cord blood vessel morphol...     Blood
84   ['Hematochezia', 'Gastrointestinal hemorrhage'...   Cardiac
101  ['Microcytic anemia', 'Anemia of inadequate pr...     Blood
179  ['Embryonal neoplasm', 'Neoplasm by histology'...  Neoplasm
213  ['Radial deviation of finger', 'Deviation of f...  Skeletal
257  ['Neoplasm of the oral cavity', 'Abnormal oral...  Neoplasm
270  ['Neoplasm of the liver', 'Abnormality of the ...  Neoplasm
312  ['Hypochromic anemia', 'Anemia of inadequate p...     Blood
340  ['Neoplasm of striated muscle', 'Abnormality o...  Neoplasm
382  ['Abnormality of the radial head', 'Abnormal m...  Skeletal
383  ['Neoplasm of the small intestine', 'Neoplasm ...  Neoplasm
386  ['Absent radius', 'Absent forearm bone', 'Apla...  Skeletal
396  ['Spontaneous hematomas', 'Subcutaneous hemorr...   Cardiac
418  ['Neuroblastic tumor', 'Malignant neoplasm of ...  Neoplasm
423  ['Primitive neuroectodermal tumor', 'Neuroepit...  Neoplasm
425  ['Peripheral primitive neuroectodermal neoplas...  Neoplasm

                                             TF_family
14                                    ['GATA', 'HOXD']
84                                            ['SMAD']
101                                    ['SMAD', 'IRX']
179                                    ['NFIX', 'MNX']
213  ['TBX', 'SMAD', 'GATA', 'HMGA', 'HOXD', 'LMX1B...
257                                            ['SOX']
270                                 ['POU6F', 'HNF1A']
312                                            ['IRX']
340                                            ['PAX']
382                                          ['LMX1B']
383                                           ['SMAD']
386                                           ['HOXD']
396                                           ['SMAD']
418                                         ['PHOX2B']
423                                         ['PHOX2B']
425                                         ['PHOX2B']
TFs actifs dans Fanconi : ['GATA', 'HMGA', 'HNF1A', 'HOXA', 'HOXD', 'IRX', 'LMX1B', 'MNX', 'NFIX', 'PAX', 'PHOX2B', 'POU6F', 'SMAD', 'SOX', 'TBX']

In [101]:
tar_term_keywords = [
    "radial", "radius",
    "anemia", "thrombocytopenia",
    "hypospadias"
]

tar_clusters = [
    "Renal",
    "Blood"
]

tf_tar = tf_union_from_terms_and_clusters(
    df,
    term_keywords=tar_term_keywords,
    clusters=[]
)

print("TFs actifs dans TAR :", sorted(tf_tar))

Nombre de termes correspondant aux mots-clés ['radial', 'radius', 'anemia', 'thrombocytopenia', 'hypospadias']:                      Gene_set                                         Term  \
101  Human_Phenotype_Ontology               Microcytic anemia (HP:0001935)
213  Human_Phenotype_Ontology      Radial deviation of finger (HP:0009466)
312  Human_Phenotype_Ontology              Hypochromic anemia (HP:0001931)
355  Human_Phenotype_Ontology                     Hypospadias (HP:0000047)
382  Human_Phenotype_Ontology  Abnormality of the radial head (HP:0003995)
386  Human_Phenotype_Ontology                   Absent radius (HP:0003974)

    Overlap   P-value  Adjusted P-value  Old P-value  Old Adjusted P-value  \
101    2/25  0.039502          0.237368            0                     0
213   8/229  0.008920          0.141338            0                     0
312    1/16  0.184348          0.356512            0                     0
355    3/84  0.090609          0.316208            0                     0
382    1/21  0.234693          0.382351            0                     0
386    1/21  0.234693          0.382351            0                     0

     Odds Ratio  Combined Score  \
101    6.833189       22.080713
213    2.884994       13.615637
312    5.220106        8.826833
355    2.913481        6.995867
382    3.914087        5.673375
386    3.914087        5.673375

                                               Genes  \
101                                       SMAD4;IRX5
213  TBX1;SMAD4;GATA6;HMGA2;HOXD13;LMX1B;HOXA13;TBX2
312                                             IRX5
355                              HNF1B;HOXD13;HOXA13
382                                            LMX1B
386                                           HOXD13

                                               Parents  \
101  ['Microcytic anemia', 'Anemia of inadequate pr...
213  ['Radial deviation of finger', 'Deviation of f...
312  ['Hypochromic anemia', 'Anemia of inadequate p...
355  ['Hypospadias', 'Displacement of the urethral ...
382  ['Abnormality of the radial head', 'Abnormal m...
386  ['Absent radius', 'Absent forearm bone', 'Apla...

                                          Parents_list   Cluster  \
101  ['Microcytic anemia', 'Anemia of inadequate pr...     Blood
213  ['Radial deviation of finger', 'Deviation of f...  Skeletal
312  ['Hypochromic anemia', 'Anemia of inadequate p...     Blood
355  ['Hypospadias', 'Displacement of the urethral ...     Renal
382  ['Abnormality of the radial head', 'Abnormal m...  Skeletal
386  ['Absent radius', 'Absent forearm bone', 'Apla...  Skeletal

                                             TF_family
101                                    ['SMAD', 'IRX']
213  ['TBX', 'SMAD', 'GATA', 'HMGA', 'HOXD', 'LMX1B...
312                                            ['IRX']
355                          ['HNF1B', 'HOXD', 'HOXA']
382                                          ['LMX1B']
386                                           ['HOXD']
TFs actifs dans TAR : ['GATA', 'HMGA', 'HNF1B', 'HOXA', 'HOXD', 'IRX', 'LMX1B', 'SMAD', 'TBX']

In [117]:
common_all = set(tf_fanconi) & set(tf_vacterl) & set(tf_tar)
common_all

{'GATA', 'HMGA', 'HOXA', 'HOXD', 'IRX', 'LMX1B', 'SMAD', 'TBX'}

In [118]:
#🧬 5. TFs communs VACTERL ↔ TAR (mais pas Fanconi)
common_vacterl_tar = set(tf_vacterl) & set(tf_tar) - set(tf_fanconi)
common_vacterl_tar

{'HNF1B'}

In [119]:
#specific to Fanconi (not in VACTERL or TAR)
set(tf_fanconi) - set(tf_vacterl) - set(tf_tar)

{'HNF1A', 'PHOX2B', 'POU6F'}

In [120]:
import networkx as nx

G = nx.Graph()

# Ajouter les trois syndromes
syndromes = ["Fanconi", "VACTERL", "TAR"]
for s in syndromes:
    G.add_node(s, type="syndrome", color="blue", size=40)

# Ajouter les TF et leurs liens
def add_tf_links(tf_set, syndrome_name):
    for tf in tf_set:
        if tf not in G.nodes:
            G.add_node(tf, type="TF", color="red", size=20)
        G.add_edge(tf, syndrome_name)

add_tf_links(tf_fanconi, "Fanconi")
add_tf_links(tf_vacterl, "VACTERL")
add_tf_links(tf_tar, "TAR")

In [121]:
from pyvis.network import Network

net = Network(
    height="900px",
    width="100%",
    bgcolor="#ffffff",
    font_color="black",
    cdn_resources="in_line"
)

# Options de physique
net.set_options("""
{
  "physics": {
    "enabled": true,
    "barnesHut": {
      "gravitationalConstant": -8000,
      "centralGravity": 0.3,
      "springLength": 95,
      "springConstant": 0.04,
      "damping": 0.09
    }
  }
}
""")

# Ajouter les nœuds
for n, data in G.nodes(data=True):
    net.add_node(
        n,
        color=data["color"],
        size=data["size"],
        title=n
    )

# Ajouter les arêtes
for u, v in G.edges():
    net.add_edge(u, v, color="gray")

net.write_html("network_tf_syndrome.html")

In [122]:
import networkx as nx
from pyvis.network import Network

G = nx.Graph()

# Ajouter les syndromes
syndromes = ["Fanconi", "VACTERL", "TAR"]
for s in syndromes:
    G.add_node(s, type="syndrome", color="blue", size=40)

# Fonction pour ajouter les TF
def add_tf_links(tf_set, syndrome_name):
    for tf in tf_set:
        if tf not in G.nodes:
            G.add_node(tf, type="TF", color="red", size=20)
        G.add_edge(tf, syndrome_name)

add_tf_links(tf_fanconi, "Fanconi")
add_tf_links(tf_vacterl, "VACTERL")
add_tf_links(tf_tar, "TAR")

# PyVis
net = Network(
    height="900px",
    width="100%",
    bgcolor="#ffffff",
    font_color="black",
    cdn_resources="in_line"
)

net.set_options("""
{
  "physics": {
    "enabled": true,
    "barnesHut": {
      "gravitationalConstant": -8000,
      "centralGravity": 0.3,
      "springLength": 95,
      "springConstant": 0.04,
      "damping": 0.09
    }
  }
}
""")

# Ajouter les nœuds
for n, data in G.nodes(data=True):
    net.add_node(
        n,
        color=data["color"],
        size=data["size"],
        title=n
    )

# Ajouter les arêtes
for u, v in G.edges():
    net.add_edge(u, v, color="gray")

net.write_html("network_tf_syndrome_final.html")

In [123]:
organ_systems = {
    "Skeletal": ["skeletal", "bone", "vertebr", "limb", "radial"],
    "Cardiac": ["cardiac", "heart"],
    "Renal": ["renal", "kidney", "ureter", "hypospadias"],
    "Blood": ["anemia", "hemato", "thrombocytopenia"],
    "GI": ["esoph", "trache", "anal", "digestive"],
    "Respiratory": ["respir", "lung", "trache"]
}
import ast

def tfs_for_organ(df, keywords):
    mask = df["Term"].str.contains("|".join(keywords), case=False, na=False)
    sub = df[mask]
    tf_set = set()
    for tf_str in sub["TF_family"]:
        for tf in ast.literal_eval(tf_str):
            if tf != "Other":
                tf_set.add(tf)
    return tf_set
import pandas as pd

# Collect all TFs from Fanconi, VACTERL, TAR
all_tfs = sorted(tf_fanconi | tf_vacterl | tf_tar)

# Build matrix
rows = []
for tf in all_tfs:
    row = {"TF": tf}
    for organ, keywords in organ_systems.items():
        row[organ] = int(tf in tfs_for_organ(df, keywords))
    rows.append(row)

df_heat = pd.DataFrame(rows).set_index("TF")
import plotly.express as px

fig = px.imshow(
    df_heat.T,
    labels=dict(x="TF", y="Organ System", color="Presence"),
    x=df_heat.index,
    y=df_heat.columns,
    color_continuous_scale=["white","red"]
)

fig.update_layout(
    title="Heatmap TF × Organ System",
    width=1400,
    height=700
)

fig.show()

In [3]:
import pandas as pd
df = pd.read_csv("/Volumes/mac1/data/limb/best_hpo_terms_with_parents_and_clusters_and_TFfamilies.csv")

In [4]:
import ast

# TF présents dans le cluster Diabetes/Glucose
diabetes_tfs = set()

for _, row in df[df["Cluster"]=="Glucose/Insulin"].iterrows():
    diabetes_tfs.update(ast.literal_eval(row["TF_family"]))

# HPO skeletiques qui partagent au moins un TF avec Diabetes
shared_hpo = []

for _, row in df[df["Cluster"]=="Skeletal"].iterrows():

    tfs = set(ast.literal_eval(row["TF_family"]))

    common = tfs & diabetes_tfs

    if len(common) > 0:
        shared_hpo.append({
            "Term": row["Term"],
            "Shared_TFs": ", ".join(sorted(common)),
            "N_shared": len(common)
        })

shared_df = pd.DataFrame(shared_hpo)
shared_df.sort_values("N_shared", ascending=False)

,Term,Shared_TFs,N_shared
23,Radial deviation of finger (HP:0009466),"GATA, LMX1B, SMAD, TBX",4
25,Intrauterine growth retardation (HP:0001511),"GATA, PDX, SMAD, TBX",4
24,Clinodactyly of the 5th finger (HP:0004209),"GATA, LMX1B, TBX",3
41,Short neck (HP:0000470),"HNF1B, SMAD, TBX",3
28,Mandibular prognathia (HP:0000303),"FOXG, HNF1B, SMAD",3
46,Brachydactyly syndrome (HP:0001156),"FOXG, GATA, SMAD",3
20,Umbilical hernia (HP:0001537),"GATA, TBX",2
8,Patellar aplasia (HP:0006443),"LMX1B, TBX",2
11,Aplasia/Hypoplasia of the patella (HP:0006498),"LMX1B, TBX",2
12,Patellar dislocation (HP:0002999),"LMX1B, TBX",2
35,Inguinal hernia (HP:0000023),"GATA, TBX",2
1,Sprengel anomaly (HP:0000912),"HNF1B, LMX1B",2
21,Malar flattening (HP:0000272),"SMAD, TBX",2
38,Talipes equinovarus (HP:0001762),"FOXG, LMX1B",2
6,Gout (HP:0001997),HNF1B,1
32,Sacral dimple (HP:0000960),TBX,1
33,Abnormality of subcutaneous fat tissue (HP:000...,PPARG,1
34,Pterygium (HP:0001059),LMX1B,1
36,Abnormality of the metopic suture (HP:0005556),FOXG,1
39,Pectus excavatum (HP:0000767),LMX1B,1
37,Thickened calvaria (HP:0002684),SMAD,1
30,Frontal bossing (HP:0002007),TBX,1
40,Abnormality of the radial head (HP:0003995),LMX1B,1
2,Long toe (HP:0010511),TBX,1
42,2-3 toe syndactyly (HP:0004691),SMAD,1
43,Cubitus valgus (HP:0002967),LMX1B,1
44,Progressive microcephaly (HP:0000253),FOXG,1
45,Limited elbow extension (HP:0001377),LMX1B,1
31,Prominent metopic ridge (HP:0005487),FOXG,1
26,Aplasia/Hypoplasia involving the musculature (...,LMX1B,1
29,Short ribs (HP:0000773),LMX1B,1
17,Reduced subcutaneous adipose tissue (HP:0003758),PPARG,1
9,Vertebral arch anomaly (HP:0008438),SMAD,1
10,Overlapping toe (HP:0001845),SMAD,1
13,Joint contractures involving the joints of the...,TBX,1
14,Flexion contracture of toe (HP:0005830),TBX,1
15,Vertebral fusion (HP:0002948),SMAD,1
16,Tetany (HP:0001281),TBX,1
18,Congenital diaphragmatic hernia (HP:0000776),GATA,1
3,Abnormal finger flexion creases (HP:0006143),LMX1B,1
19,Hypoplastic ilia (HP:0000946),SMAD,1
22,Abnormality of the wing of the ilium (HP:0011867),SMAD,1
5,Aplasia of the musculature (HP:0100854),LMX1B,1
4,Hypoplastic iliac wings (HP:0002866),SMAD,1
7,Camptodactyly of toe (HP:0001836),TBX,1
27,Broad ribs (HP:0000885),SMAD,1
0,Absent phalangeal crease (HP:0006109),LMX1B,1

In [8]:
shared_df.Term.to_list()

['Absent phalangeal crease (HP:0006109)',
 'Sprengel anomaly (HP:0000912)',
 'Long toe (HP:0010511)',
 'Abnormal finger flexion creases (HP:0006143)',
 'Hypoplastic iliac wings (HP:0002866)',
 'Aplasia of the musculature (HP:0100854)',
 'Gout (HP:0001997)',
 'Camptodactyly of toe (HP:0001836)',
 'Patellar aplasia (HP:0006443)',
 'Vertebral arch anomaly (HP:0008438)',
 'Overlapping toe (HP:0001845)',
 'Aplasia/Hypoplasia of the patella (HP:0006498)',
 'Patellar dislocation (HP:0002999)',
 'Joint contractures involving the joints of the feet (HP:0100492)',
 'Flexion contracture of toe (HP:0005830)',
 'Vertebral fusion (HP:0002948)',
 'Tetany (HP:0001281)',
 'Reduced subcutaneous adipose tissue (HP:0003758)',
 'Congenital diaphragmatic hernia (HP:0000776)',
 'Hypoplastic ilia (HP:0000946)',
 'Umbilical hernia (HP:0001537)',
 'Malar flattening (HP:0000272)',
 'Abnormality of the wing of the ilium (HP:0011867)',
 'Radial deviation of finger (HP:0009466)',
 'Clinodactyly of the 5th finger (HP:0004209)',
 'Intrauterine growth retardation (HP:0001511)',
 'Aplasia/Hypoplasia involving the musculature (HP:0001460)',
 'Broad ribs (HP:0000885)',
 'Mandibular prognathia (HP:0000303)',
 'Short ribs (HP:0000773)',
 'Frontal bossing (HP:0002007)',
 'Prominent metopic ridge (HP:0005487)',
 'Sacral dimple (HP:0000960)',
 'Abnormality of subcutaneous fat tissue (HP:0001001)',
 'Pterygium (HP:0001059)',
 'Inguinal hernia (HP:0000023)',
 'Abnormality of the metopic suture (HP:0005556)',
 'Thickened calvaria (HP:0002684)',
 'Talipes equinovarus (HP:0001762)',
 'Pectus excavatum (HP:0000767)',
 'Abnormality of the radial head (HP:0003995)',
 'Short neck (HP:0000470)',
 '2-3 toe syndactyly (HP:0004691)',
 'Cubitus valgus (HP:0002967)',
 'Progressive microcephaly (HP:0000253)',
 'Limited elbow extension (HP:0001377)',
 'Brachydactyly syndrome (HP:0001156)']

In [10]:
from collections import Counter

counter = Counter()

for _, row in df[df["Cluster"]=="Skeletal"].iterrows():
    common = set(ast.literal_eval(row["TF_family"])) & diabetes_tfs

    for tf in common:
        counter[tf] += 1

counter.most_common()

[('LMX1B', 17),
 ('TBX', 17),
 ('SMAD', 15),
 ('GATA', 7),
 ('FOXG', 6),
 ('HNF1B', 4),
 ('PPARG', 2),
 ('PDX', 1)]